### ISSUE TITLE
wakaru removes unused imports

### ISSUE THREAD

**Issue by milahu** [pionxzh/wakaru#112]
### Describe the bug

wakaru removes unused imports
but these imports can have side effects which are required

see also [Import a module for its side effects only](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only)

### Input code

```typescript
import "./x.js"; // FIXME this import is removed
import y from "./y.js"; // FIXME this import is removed
import z from "./z.js";
console.log(z);
```

### Expected behavior

keep all imports

**Comment by pionxzh** [comment]
Fixed. You can verify it on the playground. These will be released this weekend.
