### ISSUE TITLE
un-sequence-expression is incorrect

### ISSUE THREAD

**Issue by yuv420p10le** [pionxzh/wakaru#122]
### Describe the bug

Behavior is different. Comma expressions are not evaluated in the loop like they should be. The test cases are also incorrect.

### Input code

This input code is taken directly from the unit tests. The do-while test case is also incorrect but I believe this should resolve both.

```typescript
var incr = 0;
function a() { console.log("a"); return true; }
function b() { console.log("b"); return true; }
function c() { console.log("c"); return incr++ == 0; }
function d() { console.log("d"); return true; }
function e() { console.log("e"); return true; }

while (a(), b(), c()) {
    d(), e()
}
```

### Reproduction

https://wakaru.vercel.app/#eNqFkMFuwyAQRH9ltSdboZF7dZUvKT1gvHWpnMXCOG2E/O9ZhA9R5ChcFjTzhoGEFwqz84ztu0Lre8IWLyaAYxvgBM2H5u+FbRQLmKqGpBnAep79SMfRD5VGo7EWG0CguASGGBaS83pHdvtk95q0+6R9IHPdwwFOpfF9QL8f0L++mvZJekpq/vtxI0FVyU+p/GiV+9dbjDRRObSYUeHZTJPjAduEjXw7cQzXt+b4O+MqIkWzKQndefIhYvv5pZD+yz6JKZphzro4s9SVYcvoN38eq6wbJfKfUw==

### Steps to reproduce

Just unminify the above input code using wakaru

### Expected behavior

Should print the following:
```
a
b
c
d
e
a
b
c
```

### Actual behavior

Currently prints:
```
a
b
c
d
e
c
```

**Comment by pionxzh** [comment]
Thanks for the reporting. I just reviewed all the test cases. Let me know if you find other incorrect behaviors.
