### ISSUE TITLE
wrong position for default parameters

### ISSUE THREAD

**Issue by j4k0xb** [pionxzh/wakaru#124]
### Describe the bug

it appends every arguments var as a parameter instead of using the corresponding index

### Input code

```typescript
function f(e) {
  var x =
    arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  var y = arguments.length > 5 ? arguments[5] : undefined;
}
```

(snippet from [main.zip](https://github.com/j4k0xb/webcrack/files/14725959/main.zip))

### Reproduction

https://wakaru.vercel.app/#eNptjs0KgzAQhF9lu4fSghU9eEmxfRD1EHS1lrpKjKKEvHsT+ofQPQ3zzQxrcCY1tj2jiAMs+4pQYD1xqZ0H9YGOYHIGmKWCBVIvAaRqpo5Yj+GDuNE3uEAM+/3Pz+ICdmkKE1dUt0wVXLdQgLHnz+4K6b/JZFNKfOm757o2Zwywk8PQcoPCYOQ+d1G1nqLwPqJ1kLR8E4NtN/RKo8iKAGl5aeNCWjaj57VH1t0TecRaZQ==

### Steps to reproduce

Only happens with un-parameters is enabled

### Expected behavior

`y` should be the 6th parameter
```js
function f(e, x = {}, tmp1, tmp2, tmp3, y) {}
```

### Actual behavior

`y` is the 3rd parameter
```js
function f(e, x = {}, y) {}
```

**Comment by pionxzh** [comment]
Hmm ye the code should somehow insert temp variables as the placeholder.
