### ISSUE TITLE
smart-rename pass not renames property inside MemberExpression

### ISSUE THREAD

**Issue by avrnex** [pionxzh/wakaru#135]
### Describe the bug

smart-rename pass not renames property inside MemberExpression

### Input code

```typescript
function test({foo: f, bar: b}) {
  console.log(f, b, f[b]);
}
```

### Steps to reproduce

Run wakaru with input code and smart-rename pass is switched to on.

### Expected behavior

in `f[b]` `f` is renamed to `foo` and `b` is renamed to `bar`.

```typescript
function test({foo, bar}) {
  console.log(foo, bar, foo[bar]);
}
```

### Actual behavior

in `f[b]` `f` is renamed to `foo`, but `b` is **NOT** renamed to `bar`.

```typescript
function test({foo, bar}) {
  console.log(foo, bar, foo[b]);
}
```

**Comment by pionxzh** [comment]
Nice catch. Thanks for the report.
