### ISSUE TITLE
Add CLI tool

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#37]
Just stumbled across this project today, and it looks really great (both the online IDE, and the layout/structure/functionality of the code)

I was thinking it would be super useful if there was a CLI interface as well, to make it easier to run against local files without needing to write wrapper code each time.

**Comment by pionxzh** [comment]
Sure, that is on the roadmap. It will be implemented recently.

**Comment by 0xdevalias** [comment]
Awesome, thanks! :)
