### ISSUE TITLE
Over-shadowing of 'code' Variable in startUnpack Function's map Callback in packages/playground/src/pages/Uploader.vue

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#38]
I was looking at the `playground` package to understand how the unpack code was being called/what it's API looked like/etc. While looking at the `startUnpack` code, I noticed what looks like it could be a bug.

In the `startUnpack` function, there is an issue with the shadowing of the `code` variable. The function destructures `code` from the `module` object, which overshadows the `code` variable from the higher scope of the `startUnpack` function.

The issue occurs in the `startUnpack` function, specifically within the `map` callback applied to `modules`:

https://github.com/pionxzh/wakaru/blob/b06d0a7d8682042700398f0bbba1d76839fb57cf/packages/playground/src/pages/Uploader.vue#L80C1-L99C7

### Expected Behavior

We expect each module to be transformed into an object with distinct properties, where `code` is the original code from the module, and another property (possibly named `transformed`) for the processed or transformed code, without overshadowing the original `code` variable from the higher scope.

### Suggested Fix

To fix this, we should directly destructure a `transformed` (or similarly named) property from the `module` object, avoiding the overshadowing of the `code` variable. For example:

```diff
    const { modules, moduleIdMapping } = unpack(code)
    const unpackedModules = modules.map<TransformedModule>((module) => {
-       const { id, isEntry, code, tags } = module
+       const { id, isEntry, code: transformed, tags } = module
        return {
            id,
            isEntry,
            code,
-           transformed: code,
+           transformed,
            import: module.import,
            export: module.export,
            tags,
        }
    })
```

**Comment by pionxzh** [comment]
The code's behavior is intended. It will prepare `TransformedModule` with the `code` from unpack for both input(which is correct), and output(as "result" when no unminify runs). And then the `transformed` will be re-assigned in 
https://github.com/pionxzh/wakaru/blob/b06d0a7d8682042700398f0bbba1d76839fb57cf/packages/playground/src/pages/Uploader.vue#L145-L147

But the shadowing might be the bad practice that we should avoid.
