### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by jehna** [pionxzh/wakaru#39]
It seems that this project does not yet have a functioning npm package; [the one at npm](https://www.npmjs.com/package/wakaru) seems to be an empty placeholder.

I'm the developer of https://github.vom/jehna/humanify and I'd like to use Wakaru as a part of Humanify instead of webcrack (see jehna/humanify#3).

**Comment by pionxzh** [comment]
Hi, thanks for interesting in this project. The reason why there is no NPM package at first is because I thought the API would be unstable under heavy development. But I think now it shall be ok to provide a 0.x release.

May I confirm the part you need? unpack or unminify?

**Comment by pionxzh** [comment]
OK, I checked your repo, it is the unpacking part. I haven't checked the detail of `webcrack` to see which tool have better support coverage. You will need to do the test by yourself at the moment. Another strategy is choosing one tool as the fallback when no module is detected.

And you can also run unminify before sending it to GPT to reduce the syntax noise.

**Comment by 0xdevalias** [comment]
> May I confirm the part you need? unpack or unminify?

Personally I would love to see both published/available.

> But I think now it shall be ok to provide a 0.x release.

I would personally be happy with `0.x` releases with unstable API's, even if they change dramatically.

**Comment by 0xdevalias** [comment]
Looks like some progress happening on this one :)

- https://github.com/pionxzh/wakaru/commit/2c281bc29af5e609bbd352b1bde4b14d5b3122e5: `feat: build package`
- https://github.com/pionxzh/wakaru/commit/81d2c28e4276e57b15c6917b314dd86a20c11e79: `chore: add .release-please-manifest.json`

**Comment by pionxzh** [comment]
NPM package has been released. You can check the [README](https://github.com/pionxzh/wakaru#-using-the-api) for more information.

**Comment by 0xdevalias** [comment]
> it's intended to be just an internal dependency

@pionxzh Makes sense.

> that API might change a lot at any time eh

@pionxzh That makes sense. Though that was also theoretically the reason for not publishing unminify/etc as well yeah? But you ended up deciding that given it was a `0.x` release that breaking changes weren't so much of an issue.

> I would suggest anyone who wants to use it can simply copy-paste.

@pionxzh _nods_, that's fair enough.

**Comment by pionxzh** [comment]
unminify is okay for me as the public interface shall be stable. But utils will really have some massive refactoring. So ya, no plan to publish them for now.

**Comment by 0xdevalias** [comment]
> So ya, no plan to publish them for now.

@pionxzh No worries :)
