### ISSUE TITLE
Port transform passes from synchrony

### ISSUE THREAD

**Issue by mochaaP** [pionxzh/wakaru#59]
[Synchrony](https://github.com/relative/synchrony) is a deobfuscator for [javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator) and [js-confuser](https://github.com/MichaelXF/js-confuser).

It provides a few useful passes:

- DeadCode (Dead code elimination)
- ControlFlow (defeat CFG flattening)
- StringDecoder (decrypt string constants)
- etc.

However, it directly operates on Acorn AST trees, and isn't very actively maintained. It would be a big benefit for us to port the passes here.

We might want to ask the author for a relicense, since it's GPL-3.0-only.

**Comment by mochaaP** [comment]
An MIT-licensed alternative is <https://github.com/j4k0xb/webcrack>.

**Comment by pionxzh** [comment]
Wakaru's goal will not include deobfuscator-related features. I believe that every tool can do its best part.

We can bring some de-mangle or other features that are related to unminify to Wakaru (without violating the GPL license?). I knew `webcrack` project, but currently I don't see many features that we can borrow. I will check when we got an empty backlog maybe 😆

**Comment by 0xdevalias** [comment]
> I knew webcrack project, but currently I don't see many features that we can borrow.

I haven't deeply explored/compared/contrasted `webcrack` with `wakaru`; but when I first came across both projects the other day, I found that `wakaru` did a much better job for my needs in the current state than what `webcrack` could offer at the time.

**Comment by pionxzh** [comment]
Closing. If anyone finds rules from other tools that can be useful and fit into the goal of `Wakaru`, please don't hesitate to open a new issue. The recommended way would be to request for the feature and mention related work in other tools. 🙏
