### ISSUE TITLE
refactor 'leaky abstractions' related to ASTs + other AST utils into @wakaru/ast-utils

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#65]
Extracting this from a deeper comment in another issue so it doesn't get 'lost among the noise' there:

> For my own reference, here are the code locations currently referencing `jscodeshift`, `recast` and/or `ast-types`:
> 
> - https://github.com/search?q=repo%3Apionxzh%2Fwakaru+%28jscodeshift+OR+recast+OR+ast-types%29&type=code
>   - https://github.com/pionxzh/wakaru/blob/main/packages/unpacker/src/unpack.ts#L16
>     - `@wakaru/unpack` using `jscodeshift` with `babylon` parser
>   - https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/index.ts#L20
>     - `@wakaru/unminify` using `jscodeshift` with `babylon` parser
>   - etc
> 
> I also note that there is a `@wakaru/ast-utils` package that could also potentially be used to centralise some 'leaky abstractions' from these libs if we were to refactor:
> 
> - https://github.com/pionxzh/wakaru/tree/main/packages/ast-utils
> 
> And it might also potentially make sense to refactor some of these utils into that ast-utils package as well maybe?
> 
> - https://github.com/pionxzh/wakaru/tree/main/packages/unminify/src/utils
> 
> _Originally posted by @0xdevalias in https://github.com/pionxzh/wakaru/issues/32#issuecomment-1822307147_

**Comment by 0xdevalias** [comment]
I was just looking through some of the code again now, and this idea popped up in my mind again, so wanted to make sure to capture it as a proper issue.

Specifically I was looking at some of the util functions in `unminify`, and thinking they seemed generic enough that they might make sense to live in `@wakaru/ast-utils`:

- https://github.com/pionxzh/wakaru/tree/main/packages/unminify/src/utils

Skimming through the code here, these are the ones that currently stand out to me as being both AST related, and seemingly generic enough that they could make sense to be refactored into `@wakaru/ast-utils`

- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/checker.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/condition.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/decisionTree.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/import.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/insert.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/isHelperFunctionCall.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/parenthesized.ts
- https://github.com/pionxzh/wakaru/blob/main/packages/unminify/src/utils/types.ts
  - `SharedParams`

**Comment by 0xdevalias** [comment]
> This is how I usually work with them

@pionxzh That makes a lot of sense. Thanks for sharing your process :)

> I will try to move some of them, but they will still follow this practice to grow the utils naturally.

@pionxzh _nods_ yup, makes sense.

**Comment by 0xdevalias** [comment]
Stumbled across this AST lib (built on top of `recast` / `babel`) that offers some higher level AST helpers. Not sure if it would be useful directly, or just for some concepts/ideas, but figured I would link to it here in case it's useful:

- https://github.com/unjs/magicast
  - > Programmatically modify JavaScript and TypeScript source codes with a simplified, elegant and familiar syntax powered by recast and babel.
  - https://github.com/unjs/magicast#examples
  - https://github.com/unjs/magicast#high-level-helpers
    - https://github.com/unjs/magicast/tree/main/src/helpers
    - https://github.com/unjs/magicast/tree/main/test/helpers

**Comment by pionxzh** [comment]
I have done the moving. I will check Magicast. Its proxy pattern looks quite convenient.
