### ISSUE TITLE
add `/*wakaru:missing*/` annotations to imports from missing modules/files

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#77]
I was just testing the new `webcrack` web IDE ([Ref](https://github.com/j4k0xb/webcrack/issues/30#issue-2045651943)), and noticed that they annotate the unminified source to explicitly mention when a module being imported from is missing with `/*webcrack:missing*/`. This would be a cool feature for `wakaru` to support as well.

You can see the full context of how I got to this unminified step on the issue I opened there ([Ref](https://github.com/j4k0xb/webcrack/issues/30#issue-2045651943)), using this minified code ([Ref](https://github.com/0xdevalias/chatgpt-source-watch/blob/main/orig/_next/static/chunks/167-121de668c4456907.js?rgh-link-date=2023-12-18T03%3A14%3A14Z)), but here is what the annotation looks like in that unminified code:

`webcrack`'s `180.js` with the `/*webcrack:missing*/` annotation:
```js
require.d(exports, {
  Z: function () {
    return a;
  }
});
var r = require( /*webcrack:missing*/"./35250.js");
// ..snip..
```

Compared to `wakaru`'s unminified `module-180.js` without it:
```js
const { jsx } = require(35250);

// ..snip..

export default {
  Z: a,
};
```

**Comment by pionxzh** [comment]
I have been bothered by it for a while too 😄 My another idea on this would be to create a `missing-module-35250.js` empty file as the placeholder. So that we can still convert them to ESM. I'm not sure if this is the best solution or if this is good in a typical workflow.

**Comment by 0xdevalias** [comment]
> My another idea on this would be to create a `missing-module-35250.js` empty file as the placeholder. So that we can still convert them to ESM. I'm not sure if this is the best solution or if this is good in a typical workflow.

@pionxzh For a lot of my usages, I think that would end up creating more 'noise' than 'value', so if that were a feature you implemented, I think it would be best if it was optional/controllable via settings/a CLI flag/similar.

**Comment by pionxzh** [comment]
I see. No worry. Then we can do the annotations first,

**Comment by pionxzh** [comment]
Done with
```js
const foo = require(9527/* wakaru:missing */);
```

**Comment by 0xdevalias** [comment]
> Done

@pionxzh Thanks! Just gave this a go, works well :) 🎉
