### ISSUE TITLE
CLI bug: Interactive mode -> Unpacker -> Input file path -> 'Input does not exist' when using `prefix/**/*.js` glob pattern

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#81]
Trying the new CLI in interactive mode, it seems to have issues when I give it an input file path like `unpacked/**/*.js`, even though that path definitely exists (running from the root dir of this checked out repo ([Ref](https://github.com/0xdevalias/chatgpt-source-watch)))

```bash
⇒ npx @wakaru/cli

┌   Wakaru CLI v0.0.2
│
│  Run "wakaru --help" for usage options
│
◇  Select features to use (Use <space> to select, <enter> to submit)
│  Unpacker - Unpacks bundled code into separated modules
│
└  Selected features: Unpacker

┌   Unpacker
│
▲  Input file path (Supports glob patterns)
│  unpacked/**/*.js_
└  Input does not exist
```

If I change the input path to something like `unpacked/`, then the error message changes to `Input is not a file`.

While I haven't looked too deeply into it, I think there might currently be a check to ensure that the provided input is a file; but that would then break the ability to import folders and globs.

---

While it's OOS of this issue, I also noticed that it's not possible to tab complete files/paths while using the interactive mode. That may be by design, but it would probably make it more user friendly. I can open this as a separate issue if desired.

**Edit:** See:

- https://github.com/pionxzh/wakaru/issues/83

**Comment by 0xdevalias** [comment]
> While I haven't looked too deeply into it, I think there might currently be a check to ensure that the provided input is a file; but that would then break the ability to import folders and globs.

Looking at the code, this seems to be implemented here:

https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/cli.ts#L203-L218

It seems to be using the `existSync` / `statSync` functions from `fs-extra`:

- https://github.com/jprichardson/node-fs-extra/tree/11.1.1
  - https://github.com/jprichardson/node-fs-extra/blob/11.1.1/docs/pathExists-sync.md
    - > An alias for [fs.existsSync()](https://nodejs.org/api/fs.html#fs_fs_existssync_path), created for consistency with [pathExists()](https://github.com/jprichardson/node-fs-extra/blob/11.1.1/docs/pathExists.md).
      - https://nodejs.org/api/fs.html#fs_fs_existssync_path
  - ???
    - https://github.com/jprichardson/node-fs-extra/blob/acf55855580db460fd5532b22d73c4543798cd7d/lib/util/stat.js#L20-L33

---

I'm not sure if the CLI is designed to be able to be passed a folder without a glob, but if so, then these checks should accept a folder as the path.

For checking globs, I think maybe a function like `isGlobPath` or similar should be added to:

- https://github.com/pionxzh/wakaru/blob/main/packages/cli/src/path.ts

It seems `globby` is the glob matching library used, which seems to already expose a method that could be used for this `isDynamicPattern`:

- https://github.com/sindresorhus/globby
  - https://github.com/sindresorhus/globby#isdynamicpatternpatterns-options
    - > Returns a `boolean` of whether there are any special glob characters in the `patterns`.

**Comment by 0xdevalias** [comment]
> I'm not sure if the CLI is designed to be able to be passed a folder without a glob, but if so, then these checks should accept a folder as the path

The CLI calls `unpacker` here:

https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/cli.ts#L275-L278

`unpacker` has a `paths` arg, which seems to be processed as a list of full file paths; so folders aren't currently supported at this level:

https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/unpacker.ts#L15-L25

---

That said, if we wanted to enhance things to be able to specify a folder path (that would then apply a default glob, eg. `$folderPath/**/*.js`), that should be fairly easy to do. Off the top of my head, we would:

- check if the provided path is to a folder
- if so, check if the folder is within the 'allowed working directory'
- if so, append the default glob pattern to it (eg. `**/*.js`)
- allow the normal glob expansion code to process it

**Comment by 0xdevalias** [comment]
I think currently, the `isPathInside` check will fail here when given a glob/etc as well:

https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/cli.ts#L211-L214

At least, depending on how that glob is defined I suppose:

https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/path.ts#L6-L12

**Comment by pionxzh** [comment]
> I also noticed that it's not possible to tab complete files/paths while using the interactive mode. That may be by design, but it would probably make it more user friendly. I can open this as a separate issue if desired.

This one is on my todo list. Can open in another one.

**Comment by pionxzh** [comment]
The path validation in unpacker is not correct because it forgot to calculate the glob. 

And this is path validation in unminify:
https://github.com/pionxzh/wakaru/blob/3758f4810965ddb7b7b7dcf7fc02653350867a0a/packages/cli/src/cli.ts#L314-L316

**Comment by pionxzh** [comment]
My expectation on the path input would be only "file(s)" or "glob to files". I'm also not sure about the use of a passing folder...

If we don't change the design, we can improve the error message to be `Input is a folder, if you want to specific files in the folder, please use {folder}/**/*.js`.

**Comment by 0xdevalias** [comment]
> This one is on my todo list. Can open in another one.

@pionxzh Done:

- https://github.com/pionxzh/wakaru/issues/83

---

> My expectation on the path input would be only "file(s)" or "glob to files". I'm also not sure about the use of a passing folder...
> 
> If we don't change the design, we can improve the error message to be `Input is a folder, if you want to specific files in the folder, please use {folder}/**/*.js`.

@pionxzh I don't have strong feelings either way. The first way I tried to do it was just passing the input folder path, but it's not much extra effort for me to be explicit and use a glob.

If a folder path on it's own isn't allowed, then I definitely think the improved error message is a good idea.

For simplicity sake/reducing the number of options, I would probably suggest just forcing the user to use a glob + showing the improved error message.

**Comment by 0xdevalias** [comment]
Whichever way is chosen though, the validation should probably be shared between passing args via CLI flags, versus using interactive mode, as currently it looks like it (at least somewhat) works to do this:

```bash
⇒ npx @wakaru/cli unpacker unpacked --unpacker-output stage2-unpacked --perf

┌   Wakaru CLI v0.0.2
│
└  Selected features: Unpacker

┌   Unpacker
│
◇  Unpacking...
SyntaxError: Leading decorators must be attached to a class declaration. (1:5)
    at constructor (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:18018:23)
    at FlowParserMixin.raise (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:20914:23)
    at FlowParserMixin.parseDecorators (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30573:22)
    at FlowParserMixin.parseStatementLike (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30370:29)
    at FlowParserMixin.parseStatementLike (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:22799:28)
    at FlowParserMixin.parseModuleItem (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30349:21)
    at FlowParserMixin.parseBlockOrModuleBlockBody (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30976:40)
    at FlowParserMixin.parseBlockBody (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30969:14)
    at FlowParserMixin.parseProgram (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30248:14)
    at FlowParserMixin.parseTopLevel (/Users/devalias/.npm/_npx/adacf4dfcf214674/node_modules/@wakaru/cli/dist/chunk-KOQHKJQW.cjs:30238:29) {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedLeadingDecorator',
  loc: Position { line: 1, column: 5, index: 5 },
  pos: 5
}
```

---

Technically even if the user is forced to use a glob, they could write a glob that only matches a folder, so we would also need to make sure that the expanded glob path is filtered down to the list of files (assuming that isn't already being done).
