### ISSUE TITLE
CLI: improve error message for missing files

### ISSUE THREAD

**Issue by 0xdevalias** [pionxzh/wakaru#96]
Currently running the CLI with a missing file doesn't give much explanation in the error message, which can be confusing:

```shell
⇒ npx @wakaru/cli all this-doesnt-exist.js

┌   Wakaru CLI v0.0.3
│
■  this-doesnt-exist.js
```

It would be good if there was some kind of explanation text associated with this 'missing file' error condition.

**Comment by pionxzh** [comment]
It's a bug. Fixed by https://github.com/pionxzh/wakaru/commit/52cb975784b03438ed5831f2bf5a52ea67939aac

**Comment by 0xdevalias** [comment]
Ah cool, glad it was already known :)
